### ISSUE TITLE
Realizar validación con al menos 5 usuarios

### ISSUE THREAD

**Issue by Cristiancanou** [Cristiancanou/equipo3_ijfr_ppi2020#2]

**Comment by Cristiancanou** [comment]
[validaciones_completas.docx](https://github.com/Cristiancanou/equipo3_ijfr_ppi2020/files/4833493/validaciones_completas.docx)

**Comment by marthaduque** [comment]
Y las validaciones deben ser con personas diferentes a los imtegrantes del equipo y deben tener las firmas.
