### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by Cristiancanou** [Cristiancanou/equipo3_ijfr_ppi2020#3]

**Comment by Cristiancanou** [comment]
[Interpretacion.de.Requisitos_INEM.docx](https://github.com/Cristiancanou/equipo3_INEM_ETER/files/4713300/Interpretacion.de.Requisitos_INEM.docx)
En este documento esta todo lo del cuadrante 1 menos las validaciones.

**Comment by marthaduque** [comment]
Falta la mision.
